### ISSUE TITLE
CRAN packages with 'Fortran 2018 deleted feature:' warnings

### ISSUE THREAD

**Issue by rsbivand** [rsbivand/splancs#2]
@barryrowlingson may I update to meet https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/splancs-00install.html ?

**Comment by barryrowlingson** [comment]
Looks like I did a bit of work fixing the Fortran 2018 warnings a while ago, but I'd forked off cran/splancs rather than the true source here... https://github.com/cran/splancs/commit/8a62dc15852ec732794cfd200c62afa22bb346e7 - if you can use that as a start or want to attack it from scratch then fantastic!

**Comment by rsbivand** [comment]
Great, thanks, I'll copy bits of that file-by-file. I have F40 with gfortran 14, and can replicate the CRAN report locally. It used to be so nice using DO - END DO on Norsk Data Fortran (early 1980's), I had to step back from that on coming to Bergen where ther were no ND minimachines.

**Comment by rsbivand** [comment]
PR #3 created

**Comment by rsbivand** [comment]
PR #3 merged, will submit later today.

**Comment by rsbivand** [comment]
On CRAN now.
